name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock httpx

      - name: Run unit + integration tests
        env: 
          SPOTIFY_CLIENT_ID: test
          SPOTIFY_CLIENT_SECRET: test
          SPOTIFY_REDIRECT_URI: http://localhost/callback
          SPOTIFY_SCOPES: user-read-playback-state user-read-currently-playing
          ORIGINS: http://localhost
          TOKEN_URL: test
        run: pytest -v